# Generated by Django 5.2.7 on 2025-11-09 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook')], max_length=20)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('inbox_sync_status', models.CharField(default='connected', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('subject', models.TextField(blank=True)),
                ('sender', models.EmailField(max_length=254)),
                ('from_header', models.TextField(blank=True)),
                ('reply_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('return_path', models.EmailField(blank=True, max_length=254, null=True)),
                ('body_html', models.TextField(blank=True)),
                ('highlighted_body_html', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('spf_result', models.CharField(default='unknown', max_length=20)),
                ('dkim_result', models.CharField(default='unknown', max_length=20)),
                ('dmarc_policy', models.CharField(default='unknown', max_length=20)),
                ('auth_score', models.IntegerField(default=0)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='email_connector.connectedaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_engine_verdict', models.CharField(choices=[('safe', 'Safe'), ('suspicious', 'Suspicious'), ('malicious', 'Malicious')], default='safe', max_length=20)),
                ('final_action', models.CharField(choices=[('allow', 'Allow'), ('quarantine', 'Quarantine'), ('block', 'Block')], default='allow', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='email_connector.email')),
            ],
        ),
        migrations.CreateModel(
            name='EmailAuthResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spf_status', models.CharField(default='unknown', max_length=20)),
                ('dkim_status', models.CharField(default='unknown', max_length=20)),
                ('dmarc_status', models.CharField(default='unknown', max_length=20)),
                ('validation_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_result', to='email_connector.email')),
            ],
        ),
        migrations.CreateModel(
            name='QuarantinedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('released', 'Released'), ('deleted', 'Deleted')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_records', to='email_connector.email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantined_emails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('task_name', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='email_conne_event_t_a05179_idx')],
            },
        ),
        migrations.CreateModel(
            name='URLAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('source', models.CharField(default='body', max_length=50)),
                ('google_safebrowsing', models.CharField(blank=True, max_length=50, null=True)),
                ('urlhaus_status', models.CharField(blank=True, max_length=50, null=True)),
                ('urlscan_status', models.CharField(blank=True, max_length=50, null=True)),
                ('final_verdict', models.CharField(choices=[('safe', 'Safe'), ('suspicious', 'Suspicious'), ('malicious', 'Malicious')], default='safe', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_analyses', to='email_connector.email')),
            ],
        ),
        migrations.AddIndex(
            model_name='connectedaccount',
            index=models.Index(fields=['user', 'email_address'], name='email_conne_user_id_c0fb29_idx'),
        ),
        migrations.AddIndex(
            model_name='connectedaccount',
            index=models.Index(fields=['email_address', 'provider'], name='email_conne_email_a_a1545b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='connectedaccount',
            unique_together={('user', 'email_address')},
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['user', 'account'], name='email_conne_user_id_1c0127_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['message_id'], name='email_conne_message_1ae54d_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['is_suspicious'], name='email_conne_is_susp_079918_idx'),
        ),
        migrations.AddIndex(
            model_name='quarantinedemail',
            index=models.Index(fields=['user', 'status'], name='email_conne_user_id_f5f63d_idx'),
        ),
        migrations.AddIndex(
            model_name='urlanalysis',
            index=models.Index(fields=['email', 'final_verdict'], name='email_conne_email_i_2e7619_idx'),
        ),
    ]
