# Generated by Django 5.2.7 on 2025-11-11 02:23

from django.db import migrations, models


def remove_duplicate_quarantine_entries(apps, schema_editor):
    """Remove duplicate quarantine entries, keeping the oldest one for each email."""
    QuarantinedEmail = apps.get_model('email_connector', 'QuarantinedEmail')
    
    # Group by email and user, keep only the oldest entry
    from django.db.models import Min
    from collections import defaultdict
    
    # Get all quarantine entries grouped by email and user
    entries = QuarantinedEmail.objects.all().order_by('email_id', 'user_id', 'created_at')
    
    # Track which entries to keep (oldest for each email+user combination)
    keep_ids = set()
    seen = set()
    
    for entry in entries:
        key = (entry.email_id, entry.user_id)
        if key not in seen:
            # Keep the first (oldest) entry for this email+user combination
            keep_ids.add(entry.id)
            seen.add(key)
    
    # Delete all entries except the ones we're keeping
    QuarantinedEmail.objects.exclude(id__in=keep_ids).delete()


def reverse_remove_duplicates(apps, schema_editor):
    """Reverse migration - nothing to do as we can't restore deleted duplicates."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('email_connector', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_quarantine_entries, reverse_remove_duplicates),
        migrations.AlterUniqueTogether(
            name='quarantinedemail',
            unique_together={('email', 'user')},
        ),
    ]
