# Generated by Django 5.2.7 on 2025-11-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_connector', '0002_remove_duplicate_quarantine_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationresult',
            name='final_action',
            field=models.CharField(choices=[('allow', 'Allow'), ('quarantine', 'Quarantine'), ('delete', 'Delete'), ('block', 'Block')], default='allow', max_length=20),
        ),
        migrations.AlterField(
            model_name='classificationresult',
            name='rule_engine_verdict',
            field=models.CharField(choices=[('safe', 'Safe'), ('suspicious', 'Suspicious'), ('malicious', 'Malicious'), ('phishing', 'Phishing')], default='safe', max_length=20),
        ),
    ]
