# Generated by Django 5.2.7 on 2025-11-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_connector', '0003_add_phishing_verdict_and_delete_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='opened_at',
            field=models.DateTimeField(blank=True, help_text='When user opened/viewed this email', null=True),
        ),
    ]
