# Generated by Django 5.2.7 on 2025-11-11 03:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_connector', '0004_add_opened_at_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['opened_at'], name='email_conne_opened__f3bca4_idx'),
        ),
    ]
